import type { LocationType } from ".";

export const LocationsData: LocationType[] = [
  {
    id: 1,
    country: "southAfrica",
    continent: "Africa",
    flag: "/images/risk-card-yellow.png",
    risk: { totalRisk: 5, totalRiskSector: 9 },
    threatOpportunities: { threats: 60, Opportunities: 58 },
    coordinates: [-30.5595, 22.9375],
    style: { backgroundColor: "#ffd079", color: "#2C2D2E" },
  },
  {
    id: 2,
    country: "Japan",
    continent: "Asia",
    flag: "/images/risk-card-red.png",
    risk: { totalRisk: 8, totalRiskSector: 5 },
    threatOpportunities: { threats: 60, Opportunities: 58 },
    coordinates: [36.2048, 138.2529],
    style: { backgroundColor: "#fa4a4d", color: "white" },
  },
  {
    id: 3,
    country: "India",
    continent: "Asia",
    flag: "/images/risk-card-dark-red.png",
    risk: { totalRisk: 5, totalRiskSector: 9 },
    threatOpportunities: { threats: 60, Opportunities: 58 },
    coordinates: [20.5937, 78.9629],
    style: { backgroundColor: "#a82224", color: "white" },
  },
  {
    id: 4,
    country: "Australia",
    continent: "Europe",
    flag: "/images/risk-card-yellow.png",
    risk: { totalRisk: 8, totalRiskSector: 5 },
    threatOpportunities: { threats: 60, Opportunities: 58 },
    coordinates: [-25.2744, 133.7751],
    style: { backgroundColor: "#ffd079", color: "#2C2D2E" },
  },
  {
    id: 5,
    country: "Usa",
    continent: "Europe",
    flag: "/images/risk-card-green.png",
    risk: { totalRisk: 5, totalRiskSector: 9 },
    threatOpportunities: { threats: 60, Opportunities: 58 },
    coordinates: [37.0902, -95.7129],
    style: { backgroundColor: "#79ff7e", color: "#2C2D2E" },
  },
  {
    id: 6,
    country: "Brazil",
    continent: "Europe",
    flag: "/images/risk-card-yellow.png",
    risk: { totalRisk: 8, totalRiskSector: 5 },
    threatOpportunities: { threats: 60, Opportunities: 58 },
    coordinates: [-14.235, -51.9253],
    style: { backgroundColor: "#ffd079", color: "#2C2D2E" },
  },

  {
    id: 7,
    country: "China",
    continent: "Asia",
    flag: "/images/risk-card-yellow.png",
    risk: { totalRisk: 5, totalRiskSector: 9 },
    threatOpportunities: { threats: 60, Opportunities: 58 },
    coordinates: [35.8617, 104.1954],
    style: { backgroundColor: "#ffd079", color: "#2C2D2E" },
  },
  {
    id: 8,
    country: "Russia",
    continent: "Europe",
    flag: "/images/risk-card-red.png",
    risk: { totalRisk: 8, totalRiskSector: 5 },
    threatOpportunities: { threats: 60, Opportunities: 58 },
    coordinates: [61.524, 105.3188],
    style: { backgroundColor: "#fa4a4d", color: "white" },
  },
  {
    id: 9,
    country: "Germany",
    continent: "Europe",
    flag: "/images/risk-card-dark-red.png",
    risk: { totalRisk: 5, totalRiskSector: 9 },
    threatOpportunities: { threats: 60, Opportunities: 58 },
    coordinates: [51.1657, 10.4515],
    style: { backgroundColor: "#a82224", color: "white" },
  },
  {
    id: 10,
    country: "Italy",
    continent: "Europe",
    flag: "/images/risk-card-yellow.png",
    risk: { totalRisk: 8, totalRiskSector: 5 },
    threatOpportunities: { threats: 60, Opportunities: 58 },
    coordinates: [41.8719, 12.5674],
    style: { backgroundColor: "#ffd079", color: "#2C2D2E" },
  },
  {
    id: 11,
    country: "Spain",
    continent: "South Africa",
    flag: "/images/risk-card-green.png",
    risk: { totalRisk: 5, totalRiskSector: 9 },
    threatOpportunities: { threats: 60, Opportunities: 58 },
    coordinates: [40.4637, -3.7492],
    style: { backgroundColor: "#79ff7e", color: "#2C2D2E" },
  },
  {
    id: 12,
    country: "Mexico",
    continent: "Europe",
    flag: "/images/risk-card-yellow.png",
    risk: { totalRisk: 8, totalRiskSector: 5 },
    threatOpportunities: { threats: 60, Opportunities: 58 },
    coordinates: [23.6345, -102.5528],
    style: { backgroundColor: "#ffd079", color: "#2C2D2E" },
  },
];
