export default function DownloadedRisk() {
  return (
    <div className="w-full">
      <div className="w-90 p-4 md:p-8 lg:p-12 font-sans">
        {/* Header */}
        <header className="flex justify-between items-center mb-6">
          <div className="text-xl font-bold">
            <img
              src="images/logo.png"
              alt="logo"
              className="w-[10rem] md:w-[12rem]"
            />
          </div>
          <div className="text-lg font-bold">
            Generated by: <span className="font-bold">[User Full Name]</span>
          </div>
          <div className="flex flex-col">
            <p className="pb-2">[Date] [24hrs Time]</p>
            <p>AI Model [GPT 3.5]</p>
          </div>
        </header>

        {/* Risk Title */}
        <div className="bg-[#000080] text-white  p-1 mb-1 rounded-md">
          <h1 className="text-lg font-bold">Risk Title</h1>
        </div>
        <div className="my-2">
          <p className="mt-2">
            Yorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc
            vulputate libero et velit interdum...
          </p>
        </div>

        {/* Risk Description */}
        <div className="bg-[#000080] text-white  p-1 mb-1 rounded-md">
          <h2 className="text-lg font-bold">Risk Description</h2>
        </div>
        <div className="my-2">
          <p className="mt-2">
            Yorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc
            vulputate libero et velit interdum...
          </p>
        </div>

        {/* Date Pickers */}
        <div className="flex flex-col md:flex-row justify-between space-y-4 md:space-y-0 mb-6">
          <div className="w-full md:w-1/3 p-2">
            <button className="bg-[#1D98F0] block p-2 rounded-md text-white mb-2 w-1/3">
              Exposure Start Date
            </button>
            <input
              type="date"
              className="w-full p-2 border border-gray-300 rounded"
            />
          </div>
          <div className="w-full md:w-1/3 p-2">
            <button className="bg-[#1D98F0] block p-2 rounded-md text-white mb-2 w-1/3">
              Exposure End Date
            </button>
            <input
              type="date"
              className="w-full p-2 border border-gray-300 rounded"
            />
          </div>
        </div>

        {/* Causes and Effects */}
        <div className="flex flex-col md:flex-row justify-between space-y-4 md:space-y-0 mb-6">
          <div className="w-full md:w-1/2 bg-white p-4 rounded">
            <button className="bg-[#1D98F0] block p-2 rounded-md text-white mb-2 w-full">
              Causes
            </button>
            <ul>
              {[...Array(5)].map((_, i) => (
                <li key={i} className="flex justify-between items-center mb-2">
                  <span>Yorem ipsum dolor sit amet, consectetur</span>
                  <input
                    type="number"
                    className="w-12 p-1 border border-gray-300 rounded"
                    value="9"
                    readOnly
                  />
                </li>
              ))}
            </ul>
          </div>

          <div className="w-full md:w-1/2 bg-white p-4 rounded">
            <button className="bg-[#1D98F0] block p-2 rounded-md text-white mb-2 w-full">
              Effect
            </button>
            <ul>
              {[...Array(5)].map((_, i) => (
                <li key={i} className="flex justify-between items-center mb-2">
                  <span>Yorem ipsum dolor sit amet, consectetur</span>
                  <input
                    type="number"
                    className="w-12 p-1 border border-gray-300 rounded"
                    value="9"
                    readOnly
                  />
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Risk Rating */}
        <div className="flex flex-col">
          <div className="bg-[#000080] text-white  p-1 mb-1 rounded-md">
            <h2 className="text-lg font-bold">Risk Rating</h2>
          </div>
          <div className="flex space-x-4 mb-4 mt-4 items-center">
            <button className="text-xl px-5 py-4 border rounded-md">
              Probability: 4.5
            </button>
            <button className="text-xl px-5 py-4 border rounded-md">
              Impact: 4.5
            </button>
            <p className="text-xl text-black">=</p>
            <button className="text-xl px-5 py-4 border rounded-md bg-red-600">
              Current Rating: 9
            </button>
          </div>
        </div>

        {/* Risk Mitigation and Action */}
        <div className="bg-white mb-6">
          <div className="bg-[#000080] text-white  p-1 mb-1 rounded-md">
            <h2 className="text-lg font-bold">
              Risk Mitigation & Action Rating
            </h2>
          </div>
          <ul className="space-y-2 m-2">
            {[50, 30, 20].map((rating, i) => (
              <li key={i} className="flex items-center">
                <span>
                  Yorem ipsum dolor sit amet, consectetur adipiscing elit...
                </span>
                <button className="bg-[#D8E0EC] ml-5 px-4 py-2 rounded">
                  {rating}
                </button>
              </li>
            ))}
          </ul>
        </div>

        {/* Risk Heat Map */}
        <div className="bg-white mb-6">
          <div className="bg-[#000080] text-white  p-1 mb-1 rounded-md">
            <h2 className="text-lg font-bold">Risk Heat Map</h2>
          </div>
          <h3 className="font-bold mb-4"></h3>
          <div className="flex justify-center">
            <img
              src="heatmap_placeholder.png"
              alt="Risk Heat Map"
              className="max-w-full h-auto"
            />
          </div>
        </div>

        {/* Risk Bow Tie View */}
        <div className="bg-white mb-6">
          <div className="bg-[#000080] text-white  p-1 mb-1 rounded-md">
            <h2 className="text-lg font-bold">Risk Bow Tie View</h2>
          </div>
          <div className="flex justify-around">
            <div className="flex flex-col">
              <p className="text-xl">Causes</p>
              <div className="w-40 h-56 bg-[#6095C9] p-4 text-center rounded-md"></div>
            </div>
            <div className="flex flex-col">
              <p className="text-xl">Uncertainty/Event</p>
              <div className="w-40 h-60 bg-[#6095C9] p-4 text-center rounded-md"></div>
            </div>

            <div className="flex flex-col mt-5">
              <p className="text-xl">Effects</p>
              <div className="w-56 h-40 bg-[#6095C9] p-4 text-center rounded-md"></div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <footer className="text-xs text-gray-600 text-start flex flex-col mt-8">
          <span className="text-[#333399] text-lg">Disclaimer:</span>
          <p>
            The information and services provided by Hermandai are intended for
            informational and educational purposes only. While we strive to
            ensure that our AI solutions are accurate and reliable, we cannot
            guarantee that they will always perform as expected or be free from
            errors. 1. No Warranty: [Your Company Name] makes no warranties or
            representations, express or implied, regarding the accuracy,
            reliability, or completeness of the AI solutions and information
            provided. The AI services are offered on an "as-is" basis, and we
            disclaim all implied warranties, including but not limited to, the
            implied warranties of merchantability and fitness for a particular
            purpose. 2. Changes to Services: Hermandai reserves the right to
            modify or discontinue our AI solutions at any time without notice.
            We are not liable for any changes or interruptions to the services
            provided. By using our AI solutions, you acknowledge and agree to
            these terms. If you have any questions or concerns, please contact
            us at Hermandai@gmail.com. Feel free to adjust this disclaimer based
            on the specifics of your company and the services you offer!
          </p>
        </footer>
      </div>
    </div>
  );
  //   <div className="w-[100%] bg-[#FFFFFF] mr-auto ml-auto">

  //   </div>;
}
