import { cn } from "@/lib/utils";
import { DatePicker } from "antd";

const ReportHeader = () => {
  return (
    <div className="flex w-full md:flex-row flex-col gap-3 justify-between">
      <img src="/images/logo.png" className="w-" alt="logo" />
      <h4 className="font-medium md:text-2xl text-lg">
        Generated by: [User Full Name]
      </h4>
      <div className="font-medium flex flex-col gap-3 md:text-lg ">
        <h3>[Date[24hrs Time]]</h3>
        <h3>AI Model [GPT 3.5]</h3>
      </div>
    </div>
  );
};

export default ReportHeader;

const riskCauses = [
  {
    id: 1,
    title: "Yorem ipsum dolor sit amet, consectetur ",
    number: 9,
  },
  {
    id: 1,
    title:
      "Yorem ipsum dolor sit amet, consectetur Yorem ipsum dolor sit amet, consectetur adipiscing elit.",
    number: 9,
  },
  {
    id: 1,
    title:
      "Yorem ipsum dolor sit amet, consectetur Yorem ipsum dolor sit amet, consectetur adipiscing elit.",
    number: 9,
  },
  {
    id: 1,
    title:
      "Yorem ipsum dolor sit amet, consectetur Yorem ipsum dolor sit amet, consectetur adipiscing elit.",
    number: 9,
  },
  {
    id: 1,
    title:
      "Yorem ipsum dolor sit amet, consectetur Yorem ipsum dolor sit amet, consectetur adipiscing elit.",
    number: 9,
  },
  {
    id: 1,
    title:
      "Yorem ipsum dolor sit amet, consectetur Yorem ipsum dolor sit amet, consectetur adipiscing elit.",
    number: 9,
  },
];

export const ReportBody = () => {
  return (
    <div className="">
      <ReportTitle title="Risk Title" />
      <div className="h-3" />
      <Paragraph
        p="Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam cum sit architecto laborum voluptatem laboriosam dolor, eaque recusandae laudantium, officia praesentium et natus accusamus provident cupiditate repudiandae, omnis minus delectus?"
        className="md:text-xl "
      />
      <div className="h-6" />
      <ReportTitle title="Risk Description" />
      <div className="h-3" />
      <Paragraph
        p="Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam cum sit architecto laborum voluptatem laboriosam dolor, eaque recusandae laudantium, officia praesentium et natus accusamus provident cupiditate repudiandae, omnis minus delectus?"
        className=" md:text-lg "
      />
      <div className="h-6" />
      <div className=" flex md:flex-row flex-col w-full justify-center gap-6">
        <div className="flex flex-col gap-2 w-full">
          <span className="bg-[#1D98F0] text-white text-center  py-3 px-8 rounded-lg shadow-lg mb-3">
            Exposure Start Date
          </span>
          <DatePicker className="mx-auto w-[50%] scale-110" />
        </div>
        <div className="flex flex-col gap-2 w-full">
          <span className="bg-[#1D98F0] text-white text-center   py-3 px-8 rounded-lg shadow-lg mb-3">
            Exposure Start Date
          </span>
          <DatePicker className="mx-auto  w-[50%] scale-110" />
        </div>
      </div>

      <div className="mt-4 flex md:flex-row flex-col w-full justify-center gap-6">
        <div className="flex flex-col gap-2 w-full">
          <span className="bg-[#1D98F0] text-white text-center  py-3 px-8 rounded-lg shadow-lg mb-3">
            Causes
          </span>
          <div className="space-y-3 ">
            {riskCauses.map((item) => (
              <div
                className="flex justify-between items-start md:text-base text-sm gap-6"
                key={item.id}
              >
                <Paragraph p={item?.title} className=" " />
                <h4 className="border  bg-[#D8E0EC] border-[rgba(0,0,0,0.36)] md:text-lg  py-2 px-4 md:px-6 rounded-xl text-gray-500 font-semibold">
                  {item.number}
                </h4>
              </div>
            ))}
          </div>
        </div>
        <div className="flex flex-col gap-2 w-full">
          <span className="bg-[#1D98F0] text-white text-center   py-3 px-8 rounded-lg shadow-lg mb-3">
            Effect
          </span>
          <div className="space-y-3 ">
            {riskCauses.map((item) => (
              <div
                className="flex justify-between items-start md:text-base text-sm gap-6"
                key={item.id}
              >
                <Paragraph p={item?.title} className=" " />
                <h4 className="border  bg-[#D8E0EC] border-[rgba(0,0,0,0.36)] md:text-lg  py-2 px-4 md:px-6 rounded-xl text-gray-500 font-semibold">
                  {item.number}
                </h4>
              </div>
            ))}
          </div>
        </div>
      </div>
      <div className="h-6" />
      <div className="space-y-10">
        <ReportTitle title="Risk Rating" />
        <div className="w-full flex md:flex-row flex-col justify-between items-center">
          <span className="md:text-xl text-lg md:w-auto w-full px-10 py-6 border rounded-lg">
            Probability: 4.5
          </span>
          <span className="md:text-3xl text-lg  ">+</span>
          <span className="md:text-xl  text-lg md:w-auto w-full px-10 py-6 border rounded-lg">
            Impact: 4.5
          </span>
          <span className="md:text-3xl  text-lg ">=</span>
          <span className="md:text-xl bg-red-600 md:w-auto w-full text-lg  px-10 py-6 border rounded-lg">
            Current Rating: 9
          </span>
        </div>
      </div>
      <div className="h-6" />

      <div className="">
        <ReportTitle title="Risk Mitigation & Action Rating" />
        <div className="h-6" />
        <div className="space-y-2 md:w-[70%]">
          {riskCauses.slice(0, 4).map((item) => (
            <div
              className="flex justify-between items-start md:text-base text-sm gap-6"
              key={item.id}
            >
              <Paragraph p={item?.title} className=" " />
              <h4 className="border  bg-[#D8E0EC] border-[rgba(0,0,0,0.36)] md:text-lg  py-2 px-4 md:px-6 rounded-xl text-gray-500 font-semibold">
                {item.number}
              </h4>
            </div>
          ))}
        </div>
      </div>
      <div className="h-6"></div>
    </div>
  );
};

export const Paragraph = ({
  p,
  className,
}: {
  p: string;
  className?: string;
}) => <p className={cn(`w-full `, className)}>{p}</p>;

export const ReportTitle = ({ title }: { title: string }) => (
  <h3
    className={cn(
      `w-full md:text-xl text-lg bg-[#000080] text-white rounded-lg  py-2 px-3`
    )}
  >
    {title}
  </h3>
);

export const Disclamer = () => (
  <div className=" flex flex-col justify-start items-start">
    <h3
      className={cn(
        `w-full md:text-base text-sm text-left text-[#000080] font-medium rounded-lg  `
      )}
    >
      Disclaimer:{" "}
    </h3>
    <p className=" text-xs text-left font-light">
      The information and services provided by Hermandai are intended for
      informational and educational purposes only. While we strive to ensure
      that our AI solutions are accurate and reliable, we cannot guarantee that
      they will always perform as expected or be free from errors.
    </p>
    <ul className=" text-xs text-left font-light">
      <li>
        1. No Warranty: [Your Company Name] makes no warranties or
        representations, express or implied, regarding the accuracy,
        reliability, or completeness of the AI solutions and information
        provided. The AI services are offered on an "as-is" basis, and we
        disclaim all implied warranties, including but not limited to, the
        implied warranties of merchantability and fitness for a particular
        purpose.
      </li>
      <li>
        2. Changes to Services: Hermandai reserves the right to modify or
        discontinue our AI solutions at any time without notice. We are not
        liable for any changes or interruptions to the services provided.
      </li>
    </ul>
    <p className=" text-xs text-left font-light">
      By using our AI solutions, you acknowledge and agree to these terms. If
      you have any questions or concerns, please contact us at
      Hermandai@gmail.com. Feel free to adjust this disclaimer based on the
      specifics of your company and the services you offer!
    </p>
  </div>
);
